backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - label: 'Welcome'
    name: 'home'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        format: 'frontmatter'
        # editor:
          # preview: true
        fields:
          - { label: 'Title', name: 'title', widget: 'string', required: true }
          - { label: 'Content', name: 'body', widget: 'markdown', required: false }
